# Generated by Django 2.2.2 on 2022-10-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221022_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='display_order',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
